import Avatar from './assets/avatar-caminho-agua.jpg';
import Cruella from './assets/cruella.jpg';
import Divertidamente from './assets/divertidamente.jpg';
import StarWars from './assets/starwars.jpg';
import SenhorDosAneis from './assets/senhor-dos-aneis.jpg';
import Ratatouille from './assets/rato.jpg';
import PerdidoEmMarte from './assets/perdido-em-marte.jpg';
import FantasticaFabricaChocolate from './assets/a-fantastica-fabrica-chocolate.jpg';
import Coringa from './assets/joker.jpg';
import Parasita from './assets/parasita.jpg';
import AsBranquelas from './assets/as-branquelas.jpg';
import Titanic from './assets/titanic.jpg';

const cards = [
    {id: 1, nome: 'Avatar', imagem: Avatar, diretor: 'James Cameron', categoria: 'Ficcao Cientifica', pais: 'Estados Unidos', ano:  2009, descricao:"Após formar uma família, Jake Sully e Ney'tiri fazem de tudo para ficarem juntos. No entanto, eles devem sair de casa e explorar as regiões de Pandora quando uma antiga ameaça ressurge, e Jake deve travar uma guerra difícil contra os humanos."},
    {id: 2, nome: 'Cruella', imagem: Cruella, diretor: 'Craig Gillespie', categoria: 'Comedia', pais: 'Estados Unidos', ano:2021, descricao:"Inteligente, criativa e determinada, Estella quer fazer um nome para si através de seus designs e acaba chamando a atenção da Baronesa Von Hellman. Entretanto, o relacionamento delas desencadeia um curso de eventos e revelações que fazem com que Estella abrace seu lado rebelde e se torne a Cruella, uma pessoa má, elegante e voltada para a vingança."},
    {id: 3, nome: 'Divertida Mente', imagem: Divertidamente, diretor: 'Pete Docter', categoria: 'Animacao', pais: 'Estados Unidos', ano: 2015, descricao:"Com a mudança para uma nova cidade, as emoções de Riley, que tem apenas 11 anos de idade, ficam extremamente agitadas. Uma confusão na sala de controle do seu cérebro deixa a Alegria e a Tristeza de fora, afetando a vida de Riley radicalmente."},
    {id: 4, nome: 'Star Wars IV', imagem: StarWars, diretor: 'George Lucas', categoria: 'Fantasia', pais: 'Estados Unidos', ano: 1977,  descricao:"A princesa Leia é mantida refém pelas forças imperiais comandadas por Darth Vader. Luke Skywalker e o capitão Han Solo precisam libertá-la e restaurar a liberdade e a justiça na galáxia."},
    {id: 5, nome: 'O Senhor dos Aneis', imagem: SenhorDosAneis, diretor: 'Peter Jackson', categoria: 'Fantasia', pais: 'Reino Unido',ano:2001, descricao:"O Senhor dos Anéis é um livro de alta fantasia, escrito pelo escritor britânico J. R. R. Tolkien. Escrita entre 1937 e 1949, com muitas partes criadas durante a Segunda Guerra Mundial, a saga é uma continuação de O Hobbit"},
    {id: 6, nome: 'Ratatouille', imagem: Ratatouille, diretor: 'Brad Bird', categoria: 'Animacao', pais:'Estados Unidos',ano:2007, descricao:"Remy reside em Paris e possui um sofisticado paladar. Seu sonho é se tornar um chef de cozinha e desfrutar as diversas obras da arte culinária. O único problema é que ele é um rato. Quando se acha dentro de um dos restaurantes mais finos de Paris, Remy decide transformar seu sonho em realidade."},
    {id: 7, nome: 'Perdido em Marte', imagem: PerdidoEmMarte, diretor: 'Ridley Scott', categoria: 'Ficcao Cientifica', pais:'Estados Unidos',ano:2015, descricao:"O astronauta Mark Watney é enviado a uma missão para Marte, mas após uma severa tempestade, ele é dado como morto, abandonado pelos colegas e acorda sozinho no planeta inóspito com escassos suprimentos e sem saber como reencontrar os companheiros ou retornar à Terra. Ele inicia então uma dura luta pela própria sobrevivência, utilizando de todo o seu conhecimento científico para fazer contato e retornar para casa."},
    {id: 8, nome: 'A Fantástica Fábrica de Chocolate', imagem: FantasticaFabricaChocolate, diretor: 'Tim Burton', categoria: 'Fantasia', pais:'Estados Unidos', ano: 2005, descricao: "Baseado no conto de Roald Dahl, este cômico e fantástico filme segue o jovem Charlie Bucket e seu avô Joe. Eles se juntam a um pequeno grupo de ganhadores de uma competição, os quais vão para um passeio na mágica e misteriosa fábrica do excêntrico Willy Wonka. Ajudado por seus anões trabalhadores, Wonka esconde uma surpresa para durante o passeio."},
    {id: 9, nome: 'Joker', imagem: Coringa, diretor: 'Todd Phillips', categoria: 'Suspense', pais:'Estados Unidos', ano: 2019,descricao:"Isolado, intimidado e desconsiderado pela sociedade, o fracassado comediante Arthur Fleck inicia seu caminho como uma mente criminosa após assassinar três homens em pleno metrô. Sua ação inicia um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante."},
    {id: 10, nome: 'Parasita', imagem: Parasita, diretor: 'Bong Joon-ho', categoria: 'Suspense', pais:'Coreia do Sul', ano: 2019, descricao:"Toda a família de Ki-taek está desempregada, vivendo em um porão sujo e apertado. Por obra do acaso, ele começa a dar aulas de inglês para uma garota de família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe e filhos bolam um plano para se infiltrar também na abastada família, um a um. No entanto, os segredos e mentiras necessários à ascensão social cobram o seu preço."},
    {id: 11, nome: 'As Branquelas', imagem: AsBranquelas, diretor: 'Keenen Ivory Wayans', categoria: 'Comedia', pais:'Estados Unidos', ano: 2004, descricao:"Dois irmãos agentes do FBI, Marcus e Kevin Copeland, acidentalmente evitam que bandidos sejam presos em uma apreensão de drogas. Como castigo, eles são forçados a escoltar um par de socialites nos Hamptons. Porém, quando as meninas descobrem o plano da agência, se recusam a ir. Sem opções, Marcus e Kevin decidem posar como as irmãs, transformando-se de homens afro-americanos em um par de loiras."},
    {id: 12, nome: 'Titanic', imagem: Titanic, diretor: 'James Cameron', categoria: 'Drama', pais:'Reino Unido', ano: 1998, descricao:"Um artista pobre e uma jovem rica se conhecem e se apaixonam na fatídica jornada do Titanic, em 1912. Embora esteja noiva do arrogante herdeiro de uma siderúrgica, a jovem desafia sua família e amigos em busca do verdadeiro amor."}
];

export default cards;